### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarcusBarnes**
Updates checksum admin screenshot.

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2099

# What does this Pull Request do?
Updates the screenshot for the checksum configuration page.

# Additional Notes:
Screen shot in README matches that used in the wiki update: https://wiki.duraspace.org/display/ISLANDORA/Islandora+Checksum

# Interested parties
@mjordan

### CODE REVIEW

**Comment by manez** [comment]
@MarcusBarnes can you make a pull for the 7.x branch as well? We'll want this to roll ahead to 7.x-1.11 and beyond 😄

**Comment by MarcusBarnes** [comment]
@manez The pull against the 7.x branch should be in https://github.com/Islandora/islandora_checksum/pull/57.  Thanks!

**Comment by mjordan** [comment]
@DiegoPino @rosiel Travis has failed because of the PHP 5.3 issue. How do we handle this?

**Comment by manez** [comment]
@mjordan particularly in the case of readme changes, they've been getting merged with a note that Travis is failing and why.

**Comment by DiegoPino** [comment]
@mjordan the PHP issue is being handled here https://github.com/travis-ci/travis-ci/issues/8639 by BanzaiMan (Travis-CI Dev) and he already opened a pull request
https://github.com/travis-ci/travis-build/pull/1236
@jonathangreen was amazing and opened a ticket there ninja-ing me for like 15 minutes(but also being a lot nicer and effective than I could have been!!)

**Comment by DiegoPino** [comment]
@mjordan feel free to merge this one if documentation is ok for your eyes. thanks!

**Pull request merged**
