### PR TITLE
Add ability to retroactively enable checksums

### PR DESCRIPTION
**Pull request by mjordan**
@ruebot, I'll let you update the screencap linked in the README. Also, coder is showing the following code style error"

```
Line 60: No key specified for array entry; first entry specifies key [sniffer_squiz_arrays_arraydeclaration_nokeyspecified]
    ),
```

Code looks good to me - know how to fix that?

### CODE REVIEW

**Comment by mjordan** [comment]
You know how to fix it? I can't figure out what the actual problem is.

**Comment by mjordan** [comment]
OK, thanks, lemme have a go in a few minutes.

**Comment by mjordan** [comment]
OK, fixed. I'll commit, push, and issue a new PR.

**Comment by mjordan** [comment]
OK, github magic - didn't need to open new PR.

**Comment by mjordan** [comment]
You may want to update the screencap in the README.

**Comment by dmoses** [comment]
Lads ... I dl'd and tested the module.  It is working, but I did notice some odd behavior.  I selected the checksum type, selected a collection then selected Enable. It runs though a process and looks like the checksum got applied. I checked the object with fedora/admin ... no checksum got applied. The user needs to save the configuration, then select Enable for the checksums to get generated. This is obvious now, but I missed it.

**Comment by mjordan** [comment]
Correct Don, if you are running the retro function before saving the config, it will actually rip through your objects and set the checksum type to 'DISABLED' (see https://github.com/Islandora/islandora_checksum/blob/7.x/islandora_checksum.module#L132), which is what you saw happening. That is a documentation oversite that will be fixed (I'll take care of it Nick).

**Comment by mjordan** [comment]
OK, corrected.

**Pull request merged**
